version: '3.8'

services:
  cleanclode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleanclode
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - n8n_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cleanclode.rule=Host(`cleanclode.anothershadeofgrey.com`)"
      - "traefik.http.routers.cleanclode.entrypoints=web,websecure"
      - "traefik.http.routers.cleanclode.tls.certresolver=letsencrypt"
      - "traefik.http.services.cleanclode.loadbalancer.server.port=80"

networks:
  n8n_network:
    external: true
